=== zanhk/fortnite-insight/laravel_application/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "type": "array",

  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": ["name","dbType","htmlType"],
    "properties": {
      "name": {
        "description": "Age in years",
        "type": "string"
      },
      "dbType": {
        "type": "string",
        "description": "INT \u2212 A normal-sized integer that can be signed or unsigned. If signed, the allowable range is from -2147483648 to 2147483647. If unsigned, the allowable range is from 0 to 4294967295. You can specify a width of up to 11 digits.\r\n\r\nTINYINT \u2212 A very small integer that can be signed or unsigned. If signed, the allowable range is from -128 to 127. If unsigned, the allowable range is from 0 to 255. You can specify a width of up to 4 digits.\r\n\r\nSMALLINT \u2212 A small integer that can be signed or unsigned. If signed, the allowable range is from -32768 to 32767. If unsigned, the allowable range is from 0 to 65535. You can specify a width of up to 5 digits.\r\n\r\nMEDIUMINT \u2212 A medium-sized integer that can be signed or unsigned. If signed, the allowable range is from -8388608 to 8388607. If unsigned, the allowable range is from 0 to 16777215. You can specify a width of up to 9 digits.\r\n\r\nBIGINT \u2212 A large integer that can be signed or unsigned. If signed, the allowable range is from -9223372036854775808 to 9223372036854775807. If unsigned, the allowable range is from 0 to 18446744073709551615. You can specify a width of up to 20 digits.\r\n\r\nFLOAT(M,D) \u2212 A floating-point number that cannot be unsigned. You can define the display length (M) and the number of decimals (D). This is not required and will default to 10,2, where 2 is the number of decimals and 10 is the total number of digits (including decimals). Decimal precision can go to 24 places for a FLOAT.\r\n\r\nDOUBLE(M,D) \u2212 A double precision floating-point number that cannot be unsigned. You can define the display length (M) and the number of decimals (D). This is not required and will default to 16,4, where 4 is the number of decimals. Decimal precision can go to 53 places for a DOUBLE. REAL is a synonym for DOUBLE.\r\n\r\nDECIMAL(M,D) \u2212 An unpacked floating-point number that cannot be unsigned. In the unpacked decimals, each decimal corresponds to one byte. Defining the display length (M) and the number of decimals (D) is required. NUMERIC is a synonym for DECIMAL.\r\n\r\nDate and Time Types\r\nThe MySQL date and time datatypes are as follows \u2212\r\n\r\nDATE \u2212 A date in YYYY-MM-DD format, between 1000-01-01 and 9999-12-31. For example, December 30th, 1973 would be stored as 1973-12-30.\r\n\r\nDATETIME \u2212 A date and time combination in YYYY-MM-DD HH:MM:SS format, between 1000-01-01 00:00:00 and 9999-12-31 23:59:59. For example, 3:30 in the afternoon on December 30th, 1973 would be stored as 1973-12-30 15:30:00.\r\n\r\nTIMESTAMP \u2212 A timestamp between midnight, January 1st, 1970 and sometime in 2037. This looks like the previous DATETIME format, only without the hyphens between numbers; 3:30 in the afternoon on December 30th, 1973 would be stored as 19731230153000 ( YYYYMMDDHHMMSS ).\r\n\r\nTIME \u2212 Stores the time in a HH:MM:SS format.\r\n\r\nYEAR(M) \u2212 Stores a year in a 2-digit or a 4-digit format. If the length is specified as 2 (for example YEAR(2)), YEAR can be between 1970 to 2069 (70 to 69). If the length is specified as 4, then YEAR can be 1901 to 2155. The default length is 4.\r\n\r\nString Types\r\nAlthough the numeric and date types are fun, most data you'll store will be in a string format. This list describes the common string datatypes in MySQL.\r\n\r\nCHAR(M) \u2212 A fixed-length string between 1 and 255 characters in length (for example CHAR(5)), right-padded with spaces to the specified length when stored. Defining a length is not required, but the default is 1.\r\n\r\nVARCHAR(M) \u2212 A variable-length string between 1 and 255 characters in length. For example, VARCHAR(25). You must define a length when creating a VARCHAR field.\r\n\r\nBLOB or TEXT \u2212 A field with a maximum length of 65535 characters. BLOBs are \"Binary Large Objects\" and are used to store large amounts of binary data, such as images or other types of files. Fields defined as TEXT also hold large amounts of data. The difference between the two is that the sorts and comparisons on the stored data are case sensitive on BLOBs and are not case sensitive in TEXT fields. You do not specify a length with BLOB or TEXT.\r\n\r\nTINYBLOB or TINYTEXT \u2212 A BLOB or TEXT column with a maximum length of 255 characters. You do not specify a length with TINYBLOB or TINYTEXT.\r\n\r\nMEDIUMBLOB or MEDIUMTEXT \u2212 A BLOB or TEXT column with a maximum length of 16777215 characters. You do not specify a length with MEDIUMBLOB or MEDIUMTEXT.\r\n\r\nLONGBLOB or LONGTEXT \u2212 A BLOB or TEXT column with a maximum length of 4294967295 characters. You do not specify a length with LONGBLOB or LONGTEXT.\r\n\r\nENUM \u2212 An enumeration, which is a fancy term for list. When defining an ENUM, you are creating a list of items from which the value must be selected (or it can be NULL). For example, if you wanted your field to contain \"A\" or \"B\" or \"C\", you would define your ENUM as ENUM ('A', 'B', 'C') and only those values (or NULL) could ever populate that field."
      },
      "htmlType": {
        "type":"string",
        "description": "text\r\ntextarea\r\nemail\r\ndate\r\nnumber\r\npassword\r\nfile (partially supported)\tfile\r\nselect\r\nselect,value1,value2,value3\r\nselect,label1:value1,label2:value2,label3:value3\r\nselect,Daily,Weekly,Monthly\r\nselect,Sunday:0,Monday:1,Tuesday:2\r\ncheckbox\r\ncheckbox,value\r\nradio\r\nradio,label1,label2\r\nradio,label1:value1,label2:value2"
      },
      "validations": {
        "type": "string"
      },
      "type": {
        "type": "string",
        "enum": ["relation"]
      },
      "relation": {
        "description":"\"name\": \"writer_id\",\n\"dbType\": \"integer:unsigned:foreign,writers,id\",\n\"htmlType\": \"text\",\n\"relation\": \"mt1,Writer,writer_id,id\"\n\n\"relation\": \"1tm,Comment,post_id\"",
        "type": "string"
      },
      "searchable": {
        "type": "boolean"
      },
      "fillable": {
        "type": "boolean"
      },
      "primary": {
        "type": "boolean"
      },
      "inForm": {
        "type": "boolean"
      },
      "inIndex": {
        "type": "boolean"
      }
    }
  }

}

=== zanhk/fortnite-insight/laravel_application/schema/custom_fields_values.json
[
  {
    "name": "id",
    "dbType": "increments",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "primary": true,
    "fillable": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name":"value",
    "dbType": "text",
    "htmlType": "text",
    "inForm": false,
    "inIndex": false,
    "searchable": false
  },
  {
    "name": "custom_field_id",
    "dbType": "integer:unsigned:foreign,custom_fields,id",
    "htmlType": "select,1:Ok",
    "validations": "required|exists:custom_fields,id",
    "relation": "mt1,CustomField,custom_field_id,id"
  },
  {
    "name": "customizable_type",
    "dbType": "string,127",
    "htmlType":"select,User:Users",
    "validations": "required"
  },
  {
    "name": "customizable_id",
    "dbType": "integer",
    "htmlType":"number",
    "searchable": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name": "created_at",
    "dbType": "timestamp",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "fillable": false,
    "primary": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name": "updated_at",
    "dbType": "timestamp",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "fillable": false,
    "primary": false,
    "inForm": false,
    "inIndex": true
  }
]

=== zanhk/fortnite-insight/laravel_application/schema/delivery_addresses.json
[
  {
    "name": "id",
    "dbType": "increments",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "primary": true,
    "fillable": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name":"description",
    "dbType": "string,255",
    "htmlType": "text",
    "validations": "required"
  },
  {
    "name":"address",
    "dbType": "string,255",
    "htmlType": "text",
    "validations": "required"
  },
  {
    "name":"latitude",
    "dbType": "string,24",
    "htmlType": "text",
    "inIndex": false
  },
  {
    "name":"longitude",
    "dbType": "string,24",
    "htmlType": "text",
    "inIndex": false
  },
  {
    "name":"is_default",
    "dbType": "boolean",
    "htmlType": "boolean"
  },
  {
    "name": "user_id",
    "title": "user.name",
    "dbType": "integer:unsigned:foreign,users,id",
    "htmlType": "select,$user",
    "validations": "required|exists:users,id",
    "relation": "mt1,User,user_id,id"
  },
  {
    "name": "created_at",
    "dbType": "timestamp",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "fillable": false,
    "primary": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name": "updated_at",
    "dbType": "timestamp",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "fillable": false,
    "primary": false,
    "inForm": false,
    "inIndex": true
  }
]

=== zanhk/fortnite-insight/laravel_application/schema/favorite_extras.json
[
  {
    "name": "extra_id",
    "dbType": "integer:unsigned:foreign,extras,id",
    "htmlType": "number",
    "validations": "exists:extras,id",
    "primary": true
  },
  {
    "name": "favorite_id",
    "dbType": "integer:unsigned:foreign,favorites,id",
    "htmlType": "number",
    "validations": "exists:favorites,id",
    "primary": true
  }
]

=== zanhk/fortnite-insight/laravel_application/schema/cart_extras.json
[
  {
    "name": "extra_id",
    "dbType": "integer:unsigned:foreign,extras,id",
    "htmlType": "number",
    "validations": "exists:extras,id",
    "primary": true
  },
  {
    "name": "cart_id",
    "dbType": "integer:unsigned:foreign,carts,id",
    "htmlType": "number",
    "validations": "exists:carts,id",
    "primary": true
  }
]

=== zanhk/fortnite-insight/laravel_application/schema/user_restaurants.json
[
  {
    "name": "user_id",
    "dbType": "integer:unsigned:foreign,users,id",
    "htmlType": "number",
    "validations": "exists:users,id",
    "primary": true
  },
  {
    "name": "restaurant_id",
    "dbType": "integer:unsigned:foreign,restaurants,id",
    "htmlType": "number",
    "validations": "exists:restaurants,id",
    "primary": true
  }
]

=== zanhk/fortnite-insight/laravel_application/schema/food_order_extras.json
[
  {
    "name": "food_order_id",
    "dbType": "integer:unsigned:foreign,food_orders,id",
    "htmlType": "number",
    "validations": "exists:food_orders,id",
    "primary": true
  },
  {
    "name": "extra_id",
    "dbType": "integer:unsigned:foreign,extras,id",
    "htmlType": "number",
    "validations": "exists:extras,id",
    "primary": true
  },
  {
    "name":"price",
    "dbType": "double,8,2:default,0",
    "htmlType": "number",
    "validations": "required"
  }
]

=== zanhk/fortnite-insight/laravel_application/schema/users.json
[
  {
    "name": "id",
    "dbType": "increments",
    "htmlType": "",
    "validations": "",
    "searchable": true,
    "primary": true,
    "fillable": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name":"name",
    "dbType": "string,191",
    "htmlType": "text",
    "validations": "required"
  },
  {
    "name":"email",
    "dbType": "string,191",
    "htmlType": "text",
    "validations": "required"
  },
  {
    "name":"password",
    "dbType": "string,191",
    "htmlType": "text",
    "validations": "required",
    "inIndex": false
  },
  {
    "name":"api_token",
    "dbType": "string,60",
    "htmlType": "text",
    "fillable": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name": "store_id",
    "title": "store.name",
    "dbType": "integer:unsigned:foreign,stores,id",
    "htmlType": "select,$store",
    "validations": "required|exists:stores,id",
    "relation": "mt1,Store,store_id,id"
  },
  {
    "name": "role_id",
    "title": "role.name",
    "dbType": "integer:unsigned:foreign,roles,id",
    "htmlType": "select,$role",
    "validations": "required|exists:roles,id",
    "relation": "mt1,Role,role_id,id"
  },
  {
    "name":"remember_token",
    "dbType": "string,100",
    "htmlType": "text",
    "fillable": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name": "created_at",
    "dbType": "timestamp",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "fillable": false,
    "primary": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name": "updated_at",
    "dbType": "timestamp",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "fillable": false,
    "primary": false,
    "inForm": false,
    "inIndex": true
  }
]

=== zanhk/fortnite-insight/laravel_application/schema/order_statuses.json
[
  {
    "name": "id",
    "dbType": "increments",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "primary": true,
    "fillable": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name":"status",
    "dbType": "string,127",
    "htmlType": "text",
    "validations": "required"
  },
  {
    "name": "created_at",
    "dbType": "timestamp",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "fillable": false,
    "primary": false,
    "inForm": false,
    "inIndex": false
  },
  {
    "name": "updated_at",
    "dbType": "timestamp",
    "htmlType": "",
    "validations": "",
    "searchable": false,
    "fillable": false,
    "primary": false,
    "inForm": false,
    "inIndex": true
  }
]
